# Generated by Django 6.0 on 2025-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'scenario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('temp_desc', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('view_count', models.IntegerField()),
                ('download_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_url', models.TextField()),
                ('file_url', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=50)),
                ('file_version', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'scenarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioTags',
            fields=[
                ('pk', models.CompositePrimaryKey('scenario_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scenario_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pass_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=10)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
