"""
Django settings for scenariohub_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import env
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
HOST_NAME = env.HOST_NAME

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.SECRET_KEY
GEMINI_API_KEY = env.GEMINI_API_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', HOST_NAME]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'swagger_ui',                       # custom swagger
    'django_browser_reload',            # live server 구현 패키지
    'drf_yasg',                         # Swagger 사용을 위한 앱 추가
    'api',
    'rest_framework_simplejwt',         # JWT 인증을 위한 앱 추가
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',                       # CORS 처리를 위한 앱 추가: 어느 주소에서 요청이 와도 응답(외부 서버로 접근) / pip install django-cors-headers
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware', # live server 구현 미들웨어
]

ROOT_URLCONF = 'scenariohub_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scenariohub_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = env.DATABASES
DB_DSN = env.DB_DSN

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SWAGGER_SETTINGS = {
    "DEFAULT_MODEL_RENDERING": "example",  # 핵심: Model 대신 Example을 기본 탭으로
    "USE_SESSION_AUTH": False,  # Django Login 비활성화
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Bearer <access_token>",
        }
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Use our custom auth backend that rejects revoked access tokens.
        'api.auth.authentication.RevokedTokenAuthentication',
    ],
}

# Simple JWT 설정: 액세스/리프레시 토큰 수명 및 리프레시 토큰 블랙리스트 옵션
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

DATA_ROOT = BASE_DIR.parent / 'data'
TMP_DIR = BASE_DIR.parent / 'tmp'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


if os.name == 'nt':
    ESMINI_EXE = Path(env.ESMINI_BIN).resolve() / "esmini.exe"
    ODRVIEWER_EXE = Path(env.ESMINI_BIN).resolve() / "odrviewer.exe"
    DAT2CSV_EXE = Path(env.ESMINI_BIN).resolve() / "dat2csv.exe"
    OSGCONV_EXE = Path(env.OSGCONV_BIN).resolve() / "osgconv.exe"
elif os.name == 'posix':
    ESMINI_EXE = Path(env.ESMINI_BIN).resolve() / "esmini"
    ODRVIEWER_EXE = Path(env.ESMINI_BIN).resolve() / "odrviewer"
    DAT2CSV_EXE = Path(env.ESMINI_BIN).resolve() / "dat2csv"
    OSGCONV_EXE = Path(env.OSGCONV_BIN).resolve() / "osgconv"
