drop table agents;

drop table positions;

drop table speeds;

drop table actors;

drop table conditions;

drop table behaviors;

CREATE TABLE scenario_snippet.agents (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector (1024),
  code text
);

CREATE TABLE scenario_snippet.positions (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector (1024),
  code text
);

CREATE TABLE scenario_snippet.speeds (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector (1024),
  code text
);

CREATE TABLE scenario_snippet.actors (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector (1024),
  code text
);

CREATE TABLE scenario_snippet.conditions (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector (1024),
  code text
);

CREATE TABLE scenario_snippet.behaviors (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector (1024),
  code text
);

ALTER TABLE scenario_snippet.agents
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE scenario_snippet.positions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE scenario_snippet.speeds
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE scenario_snippet.actors
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE scenario_snippet.conditions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE scenario_snippet.behaviors
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

COPY scenario_snippet.agents (description, code)
FROM
  '/home/scenariohub/ScenarioHub/tmp/agents.csv'
WITH
  (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
  );

COPY scenario_snippet.positions (description, code)
FROM
  '/home/scenariohub/ScenarioHub/tmp/positions.csv'
WITH
  (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
  );

COPY scenario_snippet.speeds (description, code)
FROM
  '/home/scenariohub/ScenarioHub/tmp/speeds.csv'
WITH
  (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
  );

COPY scenario_snippet.actors (description, code)
FROM
  '/home/scenariohub/ScenarioHub/tmp/actors.csv'
WITH
  (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
  );

COPY scenario_snippet.conditions (description, code)
FROM
  '/home/scenariohub/ScenarioHub/tmp/conditions.csv'
WITH
  (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
  );

COPY scenario_snippet.behaviors (description, code)
FROM
  '/home/scenariohub/ScenarioHub/tmp/behaviors.csv'
WITH
  (
    FORMAT csv,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '"'
  );