drop table agents;
drop table positions;
drop table speeds;
drop table actors;
drop table conditions;
drop table behaviors;

CREATE TABLE public.agents (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector(1024),
  code text);
CREATE TABLE public.positions (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector(1024),
  code text);
CREATE TABLE public.speeds (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector(1024),
  code text);
CREATE TABLE public.actors (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector(1024),
  code text);
CREATE TABLE public.conditions (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector(1024),
  code text);
CREATE TABLE public.behaviors (
  id BIGINT PRIMARY KEY,
  description text,
  embedding vector(1024),
  code text);

ALTER TABLE public.agents     ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.positions  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.speeds     ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.actors     ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.behaviors  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

COPY public.agents (description, code)
FROM '/home/scenariohub/ScenarioHub/tmp/agents.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
COPY public.positions (description, code)
FROM '/home/scenariohub/ScenarioHub/tmp/positions.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
COPY public.speeds (description, code)
FROM '/home/scenariohub/ScenarioHub/tmp/speeds.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
COPY public.actors (description, code)
FROM '/home/scenariohub/ScenarioHub/tmp/actors.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
COPY public.conditions (description, code)
FROM '/home/scenariohub/ScenarioHub/tmp/conditions.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
COPY public.behaviors (description, code)
FROM '/home/scenariohub/ScenarioHub/tmp/behaviors.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');

